INSERT INTO abilities (name) VALUES 
    ('Strength'),
    ('Dexterity'),
    ('Constitution'),
    ('Intelligence'),
    ('Wisdom'),
    ('Charisma');

INSERT INTO classes (name, saving_throw_ability_1, saving_throw_ability_2) VALUES 
    ('Barbarian', 1, 3),
    ('Bard', 5, 6),
    ('Cleric', 5, 4),
    ('Druid', 5, 3),
    ('Fighter', 1, 2),
    ('Monk', 2, 3),
    ('Paladin', 1, 5),
    ('Ranger', 2, 4),
    ('Rogue', 2, 6),
    ('Sorcerer', 4, 6),
    ('Warlock', 4, 5),
    ('Wizard', 4, 1);

INSERT INTO characters (name, level, strength, dexterity, constitution, intelligence, wisdom, charisma, class_id) VALUES 
    ('Character 1', 1, 10, 12, 14, 8, 16, 13, 1),
    ('Character 2', 2, 12, 14, 10, 16, 8, 13, 2),
    ('Character 3', 3, 14, 10, 12, 8, 13, 16, 3);

INSERT INTO skills (name, ability_id) VALUES 
    ('Acrobatics', 2),
    ('Animal Handling', 6),
    ('Arcana', 4),
    ('Athletics', 1),
    ('Deception', 6),
    ('History', 4),
    ('Insight', 5),
    ('Intimidation', 6),
    ('Investigation', 4),
    ('Medicine', 5),
    ('Nature', 4),
    ('Perception', 5),
    ('Performance', 6),
    ('Persuasion', 6),
    ('Religion', 4),
    ('Sleight of Hand', 2),
    ('Stealth', 2),
    ('Survival', 5);

INSERT INTO proficiencies (character_id, skill_id) VALUES 
    (1, 1),
    (1, 4),
    (1, 8),
    (1, 9),
    (1, 12),
    (1, 13),
    (1, 15),
    (1, 17),
    (1, 18),
    (2, 2),
    (2, 3),
    (2, 5),
    (2, 6),
    (2, 7),
    (2, 10),
    (2, 11),
    (2, 14),
    (2, 16),
    (3, 1),
    (3, 4),
    (3, 8),
    (3, 9),
    (3, 12),
    (3, 13),
    (3, 15),
    (3, 17),
    (3, 18);
